name = "Zeros"
uuid = "bd1ec220-6eb4-527a-9b49-e79c3db6233b"
authors = ["Per Rutquist <per.rutquist@gmail.com>"]
version = "0.2.2"

[compat]
julia = "1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
